# Site settings
title: Les 2 Machins
email: contact@les2machins.fr
description: "Les 2 Machins"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://les2machins.fr" # the base hostname & protocol for your site
twitter_username: les2machins

# Build settings
markdown: kramdown
